import {
  BlockIcon,
  CommentIcon,
  WarningIcon,
  ShareIcon,
  SaveIcon,
  MenuIcon,
  ShareIconMobile,
  SaveIconMobile,
  CommentIconMobile,
  KarmaIcon,
  BestIcon,
  HotIcon,
  NewIcon,
  TopIcon,
  LongIcon,
  AnonIcon,
} from './icons';

export enum EIcons {
  block = 'block',
  comments = 'comments',
  warning = 'warning',
  share = 'share',
  save = 'save',
  menu = 'menu',
  shareMob = 'shareMob',
  saveMob = 'saveMob',
  commentsMob = 'commentsMob',
  karma = 'karma',
  best = 'best',
  hot = 'hot',
  new = 'new',
  top = 'top',
  long = 'long',
  anon = 'anon',
}

export const iconsMap = {
  block: BlockIcon,
  comments: CommentIcon,
  warning: WarningIcon,
  share: ShareIcon,
  save: SaveIcon,
  menu: MenuIcon,
  shareMob: ShareIconMobile,
  saveMob: SaveIconMobile,
  commentsMob: CommentIconMobile,
  karma: KarmaIcon,
  best: BestIcon,
  hot: HotIcon,
  new: NewIcon,
  top: TopIcon,
  long: LongIcon,
  anon: AnonIcon,
};
